name: Setup Node + Install
description: Checks out, sets up Node, and runs npm ci
inputs:
  node-version:
    description: Node.js version
    required: true
  registry-url:
    description: Registry URL for npm
    required: false
    default: 'https://registry.npmjs.org'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        registry-url: ${{ inputs.registry-url }}
    - name: Install dependencies
      shell: bash
      run: npm ci
