// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "api/shine-class.mdx": () => import("../content/docs/api/shine-class.mdx?collection=docs"), "api/shine-config-settings.mdx": () => import("../content/docs/api/shine-config-settings.mdx?collection=docs"), "api/shine-options.mdx": () => import("../content/docs/api/shine-options.mdx?collection=docs"), "api/use-shine-hook.mdx": () => import("../content/docs/api/use-shine-hook.mdx?collection=docs"), "examples/auto-pilot.mdx": () => import("../content/docs/examples/auto-pilot.mdx?collection=docs"), "examples/box-shadow-children.mdx": () => import("../content/docs/examples/box-shadow-children.mdx?collection=docs"), "examples/change-content.mdx": () => import("../content/docs/examples/change-content.mdx?collection=docs"), "examples/direct-class-usage.mdx": () => import("../content/docs/examples/direct-class-usage.mdx?collection=docs"), "examples/mouse-follow.mdx": () => import("../content/docs/examples/mouse-follow.mdx?collection=docs"), "examples/shadow-rgb-cookbook.mdx": () => import("../content/docs/examples/shadow-rgb-cookbook.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/nextjs-client-components.mdx": () => import("../content/docs/getting-started/nextjs-client-components.mdx?collection=docs"), "getting-started/react-quick-start.mdx": () => import("../content/docs/getting-started/react-quick-start.mdx?collection=docs"), "getting-started/vanilla-quick-start.mdx": () => import("../content/docs/getting-started/vanilla-quick-start.mdx?collection=docs"), "guides/class-api.mdx": () => import("../content/docs/guides/class-api.mdx?collection=docs"), "guides/dynamic-updates.mdx": () => import("../content/docs/guides/dynamic-updates.mdx?collection=docs"), "guides/light-position-and-intensity.mdx": () => import("../content/docs/guides/light-position-and-intensity.mdx?collection=docs"), "guides/performance-and-lifecycle.mdx": () => import("../content/docs/guides/performance-and-lifecycle.mdx?collection=docs"), "guides/react-use-shine.mdx": () => import("../content/docs/guides/react-use-shine.mdx?collection=docs"), "guides/text-vs-children.mdx": () => import("../content/docs/guides/text-vs-children.mdx?collection=docs"), "guides/troubleshooting.mdx": () => import("../content/docs/guides/troubleshooting.mdx?collection=docs"), }),
};
export default browserCollections;